### ISSUE TITLE
Multiple Y Axis

### ISSUE THREAD

**Issue by mhoulio** [spotfiresoftware/spotfire-mod-horizontalline#3]
Hi.

I could have sworn when this mod was first released you provided some guidance on how to configure a plot with multiple Y axis like the example plot in the description.  I can't seem to find that documentation anywhere.  Wondering if you can provide it again.

Thanks in advance.

**Comment by tibcoghoskins** [comment]
hi @mhoulio, here's the configuration as in the sample. It will create multiple Y-axis scales on the left and right hand side. This mod is simply wrapping the PlotlyJS API, so if you refer to that product documentation you should be able to find other ways of tweaking this. You can access the config by double-clicking in the white-space below the X-axis. Its kind of fiddly to find the right spot, so might need a bit of clicking around to hit the right spot.

`{
 "options": {
	"setYAxisColors": true
 },
 "layout": {
  "margin": {
   "t": 10,
   "r": 50,
   "b": 50,
   "l": 50
  },
  "paper_bgcolor": "transparent",
  "plot_bgcolor": "transparent",
  "shapes": [
   {
    "type": "line",
    "xref": "paper",
    "x0": 0,
    "x1": 0.95,
    "yref": "y",
    "y0": "%%RotaryRPMThreshold%%",
    "y1": "%%RotaryRPMThreshold%%",
    "line": {
     "color": "rgb(237,114,221)",
	 "dash": "dot",
     "width": 1
    }
   },
   {
    "type": "line",
    "xref": "paper",
    "x0": 0,
    "x1": 0.95,
    "yref": "y2",
    "y0": 30,
    "y1": 30,
    "line": {
     "color": "rgb(114,190,237)",
	 "dash": "dot",
     "width": 1
    }
   }
  ],
  "showlegend": false,
  "xaxis": {
   "domain": [
    0,
    0.95
   ],
   "linecolor": "#BBBBBB",
   "showgrid": false,
   "showline": true,
   "side": "bottom",
   "ticks": "outside",
   "tickangle": 0,
   "_type": "date",
   "zeroline": false
  },
  "yaxis": {
   "showgrid": true,
   "showline": true,
   "showticklabels": true,
   "ticks": "outside",
   "tickangle": 270,
   "title": {
    "text": "Rotary RPM",
    "standoff": 0
   },
   "zeroline": false
  },
  "yaxis2": {
   "anchor": "free",
   "overlaying": "y",
   "position": 0.95,
   "showgrid": false,
   "showline": true,
   "showticklabels": true,
   "side": "right",
   "ticks": "outside",
   "tickangle": 270,
   "title": {
    "text": "Engine Hours",
    "standoff": 0
   },
   "zeroline": false
  },
  "yaxis3": {
   "anchor": "free",
   "overlaying": "y",
   "position": 1,
   "showgrid": false,
   "showline": true,
   "showticklabels": true,
   "side": "right",
   "ticks": "outside",
   "tickangle": 270,
   "title": {
    "text": "Pump 1",
    "standoff": 0
   },
   "zeroline": false
  }
 },
 "options": {
  "displayModeBar": false
 },
 "defaultTrace": {
  "hoverinfo": "none",
  "line": {
   "shape": "linear",
   "width": 3
  },
  "marker": {
   "color": null,
   "size": 1
  },
  "mode": "lines+markers",
  "name": null,
  "selected": {
   "marker": {
    "size": 8
   }
  },
  "type": "scatter",
   "modPushYAxisColor": true
 },
 "traces": {
  "Rotary RPM": {
   "yaxis": "y"
  },
  "Engine Hours": {
   "yaxis": "y2"
  },
  "Pump 1": {
   "yaxis": "y3"
  }
 }
}`

**Comment by mhoulio** [comment]
Thanks so much!  I knew I could configure with PlotlyJS but I was being a
bit lazy...
